# Generated by Django 4.2.11 on 2025-03-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
